#!/usr/bin/env bash
set -e

# a shell script that runs both ./sdk/build.ts and ./secure-iframe/build.ts with the same args

rm -rf "./dist" "./secure-iframe/dist" "./sdk/dist"

if [ "$1" = "dev" ]; then
  # if first arg is dev, run them in parallel
  ./secure-iframe/build.ts "$@" &
  ./sdk/build.ts "$@" &
else
  ./secure-iframe/build.ts "$@"
  ./sdk/build.ts "$@"

  # build dts file
  pnpm tsc --noEmit false --outDir "./temp-dts" --declaration --emitDeclarationOnly --stripInternal ./sdk/src/index.ts
  pnpm api-extractor run --local --verbose
  rm -rf "./temp-dts" "./temp"
fi

