#!/bin/bash -e

# install build tools
npx pnpm@latest-10 i --frozen-lockfile

# make dist folder (only dist folder is published)
npx pnpm@latest-10 build

# modify README.md
VERSION=$(jq -r .version package.json)
sed -i.bak "s/VERSION_NUMBER_HERE/$VERSION/g" README.md

# publish to npm
npx pnpm@latest-10 publish --no-git-checks

# restore README.md
mv README.md.bak README.md
