openapi: 3.0.1
info:
  title: xendit-components-web
  description: 
  x-cortex-git:
    github:
      repository: xendit/xendit-components-web
  x-cortex-tag: xendit-components-web
  x-cortex-dependency: []
  x-cortex-service-groups:
    - P4
    - simon.paris@xendit.co
  x-cortex-owners:
    - type: EMAIL
      email: simon.paris@xendit.co
    - type: GROUP
      name: p-invoice-dev
    